### ISSUE TITLE
Error when creating TCN with default settings [Linux]

### ISSUE THREAD

**Issue by beck-weber-ing** [philipperemy/keras-tcn#267]
Could not use anymore because of this:
```
Traceback (most recent call last):
  File "/workspace/xyz/train.py", line 85, in <module>
    x = TCN(
  File "/home/xyz/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/xyz/.local/lib/python3.9/site-packages/tcn/tcn.py", line 316, in build
    self.slicer_layer.build(self.build_output_shape.as_list())
AttributeError: 'tuple' object has no attribute 'as_list'
```

Was fixed by:

```
316c316
<         self.slicer_layer.build(self.build_output_shape.as_list())
---
>         self.slicer_layer.build(list(self.build_output_shape))
```

EDIT: Host and container are Linux systems.

**Comment by thegreatesthoneybee** [comment]
What version of tensorflow are you using?
I'm using tensorflow version 2.16.2 with keras-tcn on windows 11, which is the latest version that works.

**Comment by beck-weber-ing** [comment]
I am using the 2.17 version that comes with the official tensorflow:latest-gpu docker container.

**Comment by philipperemy** [comment]
Same I don't have this problem with tensorflow 2.17 on Linux.

**Comment by thegreatesthoneybee** [comment]
I don;t have this problem al with tensorflow 2.17 on Apple M1 Ul;tra and M2 Pro. Only on windows.

**Comment by beck-weber-ing** [comment]
> Same I don't have this problem with tensorflow 2.17 on Linux.

Which Python version are you using?

**Comment by philipperemy** [comment]
@beck-weber-ing try to use python 3.10. Other versions should work as well. But just to be sure.

**Comment by van-flow** [comment]
I am still getting this error on Google Colab

tensorflow version 2.18.0
tensorflow.keras version 3.8.0
python version 3.11.11

**Comment by jonnor** [comment]
I assume you have installed from PyPI (like the documentation says)? If so, this is because the version there is from 2022. Installing from git fixed these issues for me. Ref #268

**Comment by philipperemy** [comment]
@jonnor thanks I will push a new version to PyPI soon.

**Comment by philipperemy** [comment]
Version 3.5.1 pushed to PyPI.

```
pip install keras-tcn --upgrade
```
