### ISSUE TITLE
Can this be used with tensorflow.keras?

### ISSUE THREAD

**Issue by swilson314** [philipperemy/keras-tcn#28]
Can this be used with tensorflow.keras, i.e., can I use the usual keras -> tensorflow.keras substitution?

**Comment by swilson314** [comment]
@philipperemy will do :)

**Comment by swilson314** [comment]
@philipperemy Small update, got code running but ran into error. Will keep you updated: https://stackoverflow.com/questions/53660808/stepping-into-python-code-keras-with-visual-studio-2017

**Comment by philipperemy** [comment]
@swilson314 seems like tensorflow.keras does not even support CAUSAL....

**Comment by swilson314** [comment]
@philipperemy I think maybe it does per below, and the source. My guess is that some pre-validation routine hasn't been updated.

https://www.tensorflow.org/versions/r1.10/api_docs/python/tf/keras/layers/Conv1D

padding: One of "valid", "causal" or "same" (case-insensitive). "causal" results in causal (dilated) convolutions, e.g. output[t] does not depend on input[t+1:]. Useful when modeling temporal data where the model should not violate the temporal order. See WaveNet: A Generative Model for Raw Audio, section 2.1.

**Comment by philipperemy** [comment]
At the moment, it's probably better to just:

```
pip install tensorflow-gpu
pip install keras
```

**Comment by farzinaa** [comment]
I am reopening this as there are errors with the newer versions of tf and keras (see below)
Could you please help? Thanks .

`y_true, y_pred
2020-10-05 15:35:52.156510: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-05 15:35:52.419918: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-05 15:35:52.913370: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops.cc:1115 : Not found: No algorithm worked!
2020-10-05 15:35:52.922485: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops.cc:1115 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    run_task()
  File "main.py", line 40, in run_task
    model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=15,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1088, in fit
    callbacks.on_epoch_begin(epoch)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 395, in on_epoch_begin
    callback.on_epoch_begin(epoch, numpy_logs)
  File "main.py", line 15, in on_epoch_begin
    print(np.hstack([y_test[:5], self.model.predict(x_test[:5])]))
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1599, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
	 [[node functional_1/tcn/residual_block_0/conv1D_0/conv1d (defined at /var/www/html/venvs/predictor/lib/python3.8/site-packages/tcn/tcn.py:145) ]] [Op:__inference_predict_function_1983]

Function call stack:
predict_function
`
