### ISSUE TITLE
Loading model h5 files w/ a TCN layer

### ISSUE THREAD

**Issue by porgull** [philipperemy/keras-tcn#78]
When I am using a TCN model that has been saved to an h5 file, I cannot seem to load it if tcn is imported.

Everything works as expected w/o importing tcn (minus `tcn.tcn is not loaded`, which makes sense)
```bash
(daemon) 2l4@mac105220:~/Desktop/hfp-tests/backend/ > python
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow.keras.models as m
>>> m.load_model('../out.h5')
/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py:901: UserWarning: tcn.tcn is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)
2019-10-10 13:19:56.423721: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-10 13:19:56.435709: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fce7683cd90 executing computations on platform Host. Devices:
2019-10-10 13:19:56.435729: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
<tensorflow.python.keras.engine.training.Model object at 0x1315a4fd0>
```

However, if I import the TCN layer, then try to import, Keras throws an error:
```bash
>>> from tcn import TCN
Using TensorFlow backend.
>>> m.load_model('../out.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1842, in reconstruct_from_config
    process_layer(layer_data)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1824, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py", line 887, in from_config
    return cls(**config)
  File "/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py", line 743, in __init__
    super(Lambda, self).__init__(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
>>>
```

I can get it all to work fine if I manually change `/Users/2l4/.conda/envs/daemon/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py` to use `super().__init__`, which is (theoretically) functionally equivalent.

**Comment by porgull** [comment]
oh, duh! I trained the model in a different environment with the necessary modifications to get the TCN layer working with tf2.0.0, and I forgot to reflect those changes to this new environment. When I installed keras-tcn using

```bash
pip install git+https://github.com/philipperemy/keras-tcn@tf20
```

Everything thus worked.

**Comment by nas2000co** [comment]
according to 'philipperemy'  guide for loading the "h5 " models that are content TCN layers you must add a parameter to load_model command : 

`new_model= tf.keras.models.load_model('model.h5' , custom_objects={'TCN': TCN})`

and Finish !!!!

thanks to philipperemy
